In [64]:
import torch
from transformers import BertTokenizer, BertModel

In [65]:
from transformers import BertTokenizer, BertModel

# Load pre-trained BERT model and tokenizer
tokenizer_en = BertTokenizer.from_pretrained('bert-base-uncased')
model_en = BertModel.from_pretrained('bert-base-uncased', output_attentions=True)


/Users/mh/opt/anaconda3/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [66]:
text_sample_en = "I love natural language processing."
inputs_en = tokenizer_en(text_sample_en, return_tensors='pt')
inputs_en

{'input_ids': tensor([[ 101, 1045, 2293, 3019, 2653, 6364, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [67]:
with torch.no_grad():
    outputs_en = model_en(**inputs_en)

# The hidden states are in the outputs[0]
# outputs[0] is a tensor of shape (batch_size, sequence_length, hidden_size)
hidden_states_en = outputs_en.last_hidden_state
hidden_states_en

tensor([[[-0.0419,  0.0434, -0.2534,  ..., -0.2518,  0.2330,  0.6576],
         [ 0.6340,  0.1373, -0.5598,  ..., -0.0658,  0.5974,  0.5542],
         [ 1.1149,  1.2050,  0.3571,  ..., -0.0769,  0.4818,  0.4114],
         ...,
         [ 0.7493,  0.3590, -0.4548,  ..., -0.9851, -0.3001, -0.3983],
         [ 0.5699,  0.1807, -0.3210,  ...,  0.3424, -0.4560, -0.3952],
         [ 0.7647,  0.1535, -0.1123,  ...,  0.2889, -0.6728, -0.2865]]])

In [68]:
tokens_en = tokenizer_en.convert_ids_to_tokens(inputs_en['input_ids'].squeeze().tolist())
tokens_en

['[CLS]', 'i', 'love', 'natural', 'language', 'processing', '.', '[SEP]']

In [69]:
# Get the embeddings of the [CLS] token 
cls_embedding_en = hidden_states_en[0][0]  # Assuming batch size 1
cls_embedding_en

tensor([-4.1901e-02,  4.3428e-02, -2.5336e-01, -3.5017e-01, -3.7435e-01,
        -2.3288e-01,  1.4841e-01,  6.8293e-01,  1.4665e-01, -3.0922e-01,
         7.1789e-02,  2.0524e-01,  1.3312e-01,  8.5663e-02,  2.0476e-01,
         5.6024e-03, -1.1869e-01,  4.1256e-01,  1.0981e-01, -2.5657e-02,
         1.0278e-01, -2.0408e-01,  4.0388e-02, -1.1713e-01,  2.6896e-01,
        -1.5852e-01, -6.0260e-02, -5.0208e-02,  4.9385e-03, -5.6309e-02,
        -4.2484e-02,  2.2042e-01, -2.2123e-01,  1.6162e-03,  2.1321e-01,
        -1.8850e-01, -2.2669e-02, -3.3455e-01,  1.2029e-01,  7.7284e-02,
        -8.9116e-02, -1.8291e-01,  4.9273e-02, -1.9783e-02, -1.1227e-01,
        -2.7503e-01, -3.2009e+00, -8.2603e-02, -3.4795e-01, -1.8395e-01,
         3.2589e-01, -2.3483e-02,  3.5890e-01,  3.0696e-01,  2.1356e-01,
         2.1671e-01, -2.3139e-01,  4.3008e-01,  6.2947e-02,  1.8865e-01,
         3.5517e-01,  1.8077e-01, -2.1450e-02,  8.5538e-02, -1.4239e-01,
        -4.9344e-02, -4.1498e-01,  1.6885e-01,  1.0

In [70]:
outputs2 = model_en(**inputs_en)

# Extract attention weights
attention_en = outputs2.attentions  # List of tensors with shape (batch_size, num_heads, seq_length, seq_length)
from bertviz import head_view
head_view(attention_en, tokenizer_en.convert_ids_to_tokens(inputs_en['input_ids'][0]))


<IPython.core.display.Javascript object>

In [71]:
for i, attention in enumerate(attention_en):
    print(f"Layer {i+1} attention shape: {attention.shape}")

# Example: Print the attention scores of the first head in the first layer
print("Attention scores of the first head in the first layer:")
print(attention_en[0][0][0])

Layer 1 attention shape: torch.Size([1, 12, 8, 8])
Layer 2 attention shape: torch.Size([1, 12, 8, 8])
Layer 3 attention shape: torch.Size([1, 12, 8, 8])
Layer 4 attention shape: torch.Size([1, 12, 8, 8])
Layer 5 attention shape: torch.Size([1, 12, 8, 8])
Layer 6 attention shape: torch.Size([1, 12, 8, 8])
Layer 7 attention shape: torch.Size([1, 12, 8, 8])
Layer 8 attention shape: torch.Size([1, 12, 8, 8])
Layer 9 attention shape: torch.Size([1, 12, 8, 8])
Layer 10 attention shape: torch.Size([1, 12, 8, 8])
Layer 11 attention shape: torch.Size([1, 12, 8, 8])
Layer 12 attention shape: torch.Size([1, 12, 8, 8])
Attention scores of the first head in the first layer:
tensor([[0.0825, 0.0700, 0.0490, 0.0525, 0.0813, 0.0887, 0.1741, 0.4018],
        [0.1849, 0.1299, 0.1491, 0.1112, 0.0820, 0.1878, 0.0709, 0.0842],
        [0.2121, 0.1041, 0.0681, 0.0806, 0.0559, 0.1804, 0.1362, 0.1625],
        [0.0293, 0.0989, 0.1270, 0.0837, 0.1791, 0.3409, 0.0897, 0.0514],
        [0.0539, 0.1702, 0.1546, 0

In [72]:
# Load pre-trained Turkish BERT model and tokenizer
model_name_tr = 'dbmdz/bert-base-turkish-uncased'
tokenizer_tr = BertTokenizer.from_pretrained(model_name_tr)
model_tr = BertModel.from_pretrained(model_name_tr, output_attentions=True)

# Sample Turkish text
text_tr = "Doğal dil işleme çalışmalarını seviyorum"

# Tokenize input text
inputs_tr = tokenizer_tr(text_tr, return_tensors='pt')

inputs_tr = tokenizer_tr(text_tr, return_tensors='pt', padding='max_length', truncation=True, max_length=13)


# Get model outputs including attention weights
outputs_tr = model_tr(**inputs_tr)

# Extract attention weights
attention_tr = outputs_tr.attentions  # List of tensors with shape (batch_size, num_heads, seq_length, seq_length)

# Visualize the attention weights for the first layer
head_view(attention_tr, tokenizer_tr.convert_ids_to_tokens(inputs_tr['input_ids'][0]))

<IPython.core.display.Javascript object>

In [88]:
for i, attention in enumerate(attention_tr):
    print(f"Layer {i+1} attention shape: {attention.shape}")

# Example: Print the attention scores of the first head in the first layer
print("Attention scores of the first head in the first layer:")
print(attention_tr[0][0][0])

Layer 1 attention shape: torch.Size([1, 12, 13, 13])
Layer 2 attention shape: torch.Size([1, 12, 13, 13])
Layer 3 attention shape: torch.Size([1, 12, 13, 13])
Layer 4 attention shape: torch.Size([1, 12, 13, 13])
Layer 5 attention shape: torch.Size([1, 12, 13, 13])
Layer 6 attention shape: torch.Size([1, 12, 13, 13])
Layer 7 attention shape: torch.Size([1, 12, 13, 13])
Layer 8 attention shape: torch.Size([1, 12, 13, 13])
Layer 9 attention shape: torch.Size([1, 12, 13, 13])
Layer 10 attention shape: torch.Size([1, 12, 13, 13])
Layer 11 attention shape: torch.Size([1, 12, 13, 13])
Layer 12 attention shape: torch.Size([1, 12, 13, 13])
Attention scores of the first head in the first layer:
tensor([[0.0897, 0.1166, 0.0348, 0.0386, 0.1635, 0.0978, 0.0696, 0.1640, 0.0860,
         0.0459, 0.0591, 0.0344, 0.0000],
        [0.1104, 0.0475, 0.0498, 0.1126, 0.0683, 0.0914, 0.0827, 0.0530, 0.0423,
         0.1170, 0.1173, 0.1078, 0.0000],
        [0.0753, 0.0889, 0.0678, 0.1310, 0.0881, 0.0972, 0.1

In [74]:
# Ensure padding/truncation
inputs_tr = tokenizer_tr(text_tr, return_tensors='pt', padding='max_length', truncation=True, max_length=13)


In [75]:
from bertviz import head_view

# Convert input IDs to tokens
tokens_tr = tokenizer_tr.convert_ids_to_tokens(inputs_tr['input_ids'][0])
tokens_tr
# Visualize the attention weights for the first layer
#head_view(attention_tr[0], tokens_tr)

['[CLS]',
 'dog',
 '##al',
 'dil',
 'is',
 '##leme',
 'calı',
 '##sm',
 '##alar',
 '##ını',
 'seviyorum',
 '[SEP]',
 '[PAD]']

tokens_tr = tokenizer_tr.convert_ids_to_tokens(inputs_tr['input_ids'][0])

#Check lengths
print(f"Number of tokens: {len(tokens_tr)}")
print(f"Attention length: {attention_tr[0].size(1)}")

#Visualize attention weights
head_view(attention_tr[0], tokens_tr)

In [76]:
import torch
from torchviz import make_dot

# Example input
inputs = tokenizer_ch("女人擁抱了男人.", return_tensors="pt")

# Forward pass
outputs = model_ch(**inputs)

# Generate a computation graph
y = outputs.last_hidden_state
make_dot(y, params=dict(model_tr.named_parameters())).render("bert_model_chinese_trad", format="png")


'bert_model_chinese_trad.png'

In [78]:
# Load pre-trained mandarin BERT model and tokenizer
tokenizer_ch = BertTokenizer.from_pretrained('bert-base-chinese')
model_ch = BertModel.from_pretrained('bert-base-chinese', output_attentions=True)

# Sample mandarin text
text_ch = "我喜欢学习自然语言处理"

# Tokenize input text
inputs_ch = tokenizer_ch(text_ch, return_tensors='pt')

# Get model outputs including attention weights
outputs_ch = model_ch(**inputs_ch)

# Extract attention weights
attention_ch = outputs_ch.attentions  # List of tensors with shape (batch_size, num_heads, seq_length, seq_length)

# Visualize the attention weights for the first layer
head_view(attention_ch, tokenizer_ch.convert_ids_to_tokens(inputs_ch['input_ids'][0]))

/Users/mh/opt/anaconda3/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


<IPython.core.display.Javascript object>

In [79]:
for i, attention in enumerate(attention_ch):
    print(f"Layer {i+1} attention shape: {attention.shape}")

# Example: Print the attention scores of the first head in the first layer
print("Attention scores of the first head in the first layer:")
print(attention_ch[0][0][0])

Layer 1 attention shape: torch.Size([1, 12, 13, 13])
Layer 2 attention shape: torch.Size([1, 12, 13, 13])
Layer 3 attention shape: torch.Size([1, 12, 13, 13])
Layer 4 attention shape: torch.Size([1, 12, 13, 13])
Layer 5 attention shape: torch.Size([1, 12, 13, 13])
Layer 6 attention shape: torch.Size([1, 12, 13, 13])
Layer 7 attention shape: torch.Size([1, 12, 13, 13])
Layer 8 attention shape: torch.Size([1, 12, 13, 13])
Layer 9 attention shape: torch.Size([1, 12, 13, 13])
Layer 10 attention shape: torch.Size([1, 12, 13, 13])
Layer 11 attention shape: torch.Size([1, 12, 13, 13])
Layer 12 attention shape: torch.Size([1, 12, 13, 13])
Attention scores of the first head in the first layer:
tensor([[5.8245e-04, 9.1081e-04, 2.3120e-03, 9.2217e-04, 1.7794e-03, 6.2090e-04,
         7.7457e-04, 1.0950e-03, 9.2313e-04, 7.5261e-04, 2.0951e-03, 1.5785e-03,
         9.8565e-01],
        [4.0405e-02, 1.4047e-01, 4.0320e-02, 7.5278e-02, 6.0451e-02, 1.1109e-01,
         3.6475e-02, 5.1323e-02, 7.7248e-

In [95]:
import numpy as np

# Convert attention weights to numpy array
attention_np_ch = [att.detach().numpy() for att in attention_ch]

# Compute average attention across all heads and layers
average_attention_ch = np.mean(attention_np_ch, axis=(0, 1))

# Print average attention weights
print(average_attention_ch)


[[[0.19393359 0.06906086 0.04748296 ... 0.02548706 0.02470348 0.487352  ]
  [0.14666636 0.11337259 0.0812192  ... 0.0245854  0.02879383 0.3567697 ]
  [0.08609962 0.16837615 0.07185287 ... 0.028589   0.03201407 0.34641576]
  ...
  [0.14258365 0.01799785 0.01798198 ... 0.04622106 0.09127334 0.41784474]
  [0.04918672 0.06319544 0.03055934 ... 0.17709704 0.05773009 0.35379407]
  [0.22982395 0.00947325 0.00736686 ... 0.00908571 0.01296465 0.67099404]]

 [[0.17791943 0.10409146 0.03891155 ... 0.0249285  0.06691787 0.42296043]
  [0.18528028 0.065581   0.07163843 ... 0.0119068  0.05869156 0.46691456]
  [0.10506717 0.13651687 0.08214551 ... 0.01008223 0.05251996 0.34901747]
  ...
  [0.06655802 0.02129569 0.03421057 ... 0.058527   0.14888771 0.27743927]
  [0.15099004 0.05481321 0.02980225 ... 0.13355117 0.06048786 0.3473359 ]
  [0.0984248  0.01383634 0.01168888 ... 0.01047281 0.01169868 0.7919468 ]]

 [[0.2641857  0.06096449 0.01423646 ... 0.01500112 0.03618163 0.5152266 ]
  [0.18258648 0.135547

In [96]:
from transformers import BertTokenizer, BertModel
import torch
import numpy as np

# Load pre-trained model and tokenizer
model_name = 'bert-base-uncased'
#model_name = 'bert-base-chinese'
#model_name = 'dbmdz/bert-base-turkish-uncased'

tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertModel.from_pretrained(model_name, output_hidden_states=True)

# Example sentence and POS tags
sentence = "The quick brown fox jumps over the lazy dog"
pos_tags = ["DET", "ADJ", "ADJ", "NOUN", "VERB", "ADP", "DET", "ADJ", "NOUN"]

# Convert POS tags to numerical labels (this should be consistent across your dataset)
pos_tag_to_id = {"DET": 0, "ADJ": 1, "NOUN": 2, "VERB": 3, "ADP": 4}
labels = [pos_tag_to_id[tag] for tag in pos_tags]



labels = [pos_tag_to_id[tag] for tag in pos_tags]

# Tokenize the sentence
inputs = tokenizer(sentence, return_tensors='pt')

# Forward pass to get hidden states
with torch.no_grad():
    outputs = model(**inputs)
    hidden_states = outputs.hidden_states  # tuple of (num_layers, batch_size, seq_length, hidden_size)

# Choose a specific layer (e.g., layer 3)
layer_idx = 3
layer_output = hidden_states[layer_idx]  # (batch_size, seq_length, hidden_size)

# Extract features for the tokens (excluding special tokens like [CLS] and [SEP])
token_features = layer_output[0, 1:-1, :]  # (seq_length - 2, hidden_size)

# Convert token features to numpy array
token_features_np = token_features.numpy()


/Users/mh/opt/anaconda3/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [97]:
from sklearn.linear_model import LogisticRegression

# Define the probing model
probe = LogisticRegression(max_iter=1000)

# Train the probing model
probe.fit(token_features_np, labels)

# Make predictions on the same data
predictions = probe.predict(token_features_np)

# Print predictions
print("Predicted labels:", predictions)

# Convert predictions back to POS tags
id_to_pos_tag = {v: k for k, v in pos_tag_to_id.items()}
predicted_tags = [id_to_pos_tag[pred] for pred in predictions]

print("Predicted POS tags:", predicted_tags)


Predicted labels: [0 1 1 2 3 4 0 1 2]
Predicted POS tags: ['DET', 'ADJ', 'ADJ', 'NOUN', 'VERB', 'ADP', 'DET', 'ADJ', 'NOUN']


In [98]:
from sklearn.metrics import accuracy_score

# Calculate accuracy
accuracy = accuracy_score(labels, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 100.00%




#Load pre-trained Chinese BERT model and tokenizer
model_name = 'bert-base-chinese'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertModel.from_pretrained(model_name, output_hidden_states=True)

#Example sentence and POS tags
sentence = "快速 的 棕色 狐狸 跳 过 懒惰 的 狗"
pos_tags = ["ADJ", "DEC", "ADJ", "NOUN", "VERB", "PREP", "ADJ", "DEC", "NOUN"]

#Convert POS tags to numerical labels (this should be consistent across your dataset)
pos_tag_to_id = {"ADJ": 0, "DEC": 1, "NOUN": 2, "VERB": 3, "PREP": 4}
labels = [pos_tag_to_id[tag] for tag in pos_tags]

#Tokenize the sentence
inputs = tokenizer(sentence, return_tensors='pt')

#Forward pass to get hidden states
with torch.no_grad():
    outputs = model(**inputs)
    hidden_states = outputs.hidden_states  # tuple of (num_layers, batch_size, seq_length, hidden_size)


layer_idx = 3
layer_output = hidden_states[layer_idx]  # (batch_size, seq_length, hidden_size)

#Extract features for the tokens 
token_features = layer_output[0, 1:-1, :]  # (seq_length - 2, hidden_size)

token_features_np = token_features.numpy()
probe = LogisticRegression(max_iter=1000)

#Train the probing model
probe.fit(token_features_np, labels)

#Make predictions on the same data
predictions = probe.predict(token_features_np)

#Convert predictions back to POS tags
id_to_pos_tag = {v: k for k, v in pos_tag_to_id.items()}
predicted_tags = [id_to_pos_tag[pred] for pred in predictions]

print("Predicted POS tags:", predicted_tags)

accuracy = accuracy_score(labels, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")


In [99]:
import stanza
from graphviz import Digraph

# Download and load the Chinese model
stanza.download('zh')
nlp = stanza.Pipeline(lang='zh', processors='tokenize,pos,lemma,depparse')

text_ch = "我喜欢学习自然语言处理"
doc_ch = nlp(text_ch)

# Function to visualize the dependency tree
def visualize_dependency_tree(doc):
    dot = Digraph()

    for sentence in doc.sentences:
        for word in sentence.words:
            dot.node(str(word.id), word.text)
            if word.head > 0:
                dot.edge(str(word.head), str(word.id), label=word.deprel)

    return dot

# Extract and print dependency relations
for sentence in doc_ch.sentences:
    print(f"Sentence: {sentence.text}")
    for word in sentence.words:
        print(f"Word: {word.text}, Head: {word.head}, Relation: {word.deprel}")

dot = visualize_dependency_tree(doc_ch)
dot.render('dependency_tree_ch', format='png', view=True)  


2024-08-01 22:52:50 INFO: Downloaded file to /Users/mh/stanza_resources/resources.json
2024-08-01 22:52:50 INFO: "zh" is an alias for "zh-hans"
2024-08-01 22:52:50 INFO: Downloading default packages for language: zh-hans (Simplified_Chinese) ...
2024-08-01 22:52:54 INFO: File exists: /Users/mh/stanza_resources/zh-hans/default.zip
2024-08-01 22:53:07 INFO: Finished downloading models and saved to /Users/mh/stanza_resources
2024-08-01 22:53:07 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES


2024-08-01 22:53:08 INFO: Downloaded file to /Users/mh/stanza_resources/resources.json
2024-08-01 22:53:08 INFO: "zh" is an alias for "zh-hans"
2024-08-01 22:53:10 INFO: Loading these models for language: zh-hans (Simplified_Chinese):
| Processor | Package          |
--------------------------------
| tokenize  | gsdsimp          |
| pos       | gsdsimp_charlm   |
| lemma     | gsdsimp_nocharlm |
| depparse  | gsdsimp_charlm   |

2024-08-01 22:53:10 INFO: Using device: cpu
2024-08-01 22:53:10 INFO: Loading: tokenize
2024-08-01 22:53:10 INFO: Loading: pos
2024-08-01 22:53:17 INFO: Loading: lemma
2024-08-01 22:53:17 INFO: Loading: depparse
2024-08-01 22:53:18 INFO: Done loading processors!


Sentence: 我喜欢学习自然语言处理
Word: 我, Head: 2, Relation: nsubj
Word: 喜欢, Head: 0, Relation: root
Word: 学习, Head: 6, Relation: advcl
Word: 自然, Head: 5, Relation: nmod
Word: 语言, Head: 3, Relation: obj
Word: 处理, Head: 2, Relation: xcomp


'dependency_tree_ch.png'

In [100]:
# Download and load the Chinese model
stanza.download('en')
nlp2 = stanza.Pipeline(lang='en', processors='tokenize,pos,lemma,depparse')

text_en = "I love learning about natural language processing"
doc_en = nlp2(text_en)

# Function to visualize the dependency tree
def visualize_dependency_tree(doc):
    dot = Digraph()

    for sentence in doc.sentences:
        for word in sentence.words:
            dot.node(str(word.id), word.text)
            if word.head > 0:
                dot.edge(str(word.head), str(word.id), label=word.deprel)

    return dot

# Extract and print dependency relations
for sentence in doc_en.sentences:
    print(f"Sentence: {sentence.text}")
    for word in sentence.words:
        print(f"Word: {word.text}, Head: {word.head}, Relation: {word.deprel}")

dot = visualize_dependency_tree(doc_en)
dot.render('dependency_tree_en', format='png', view=True)  


2024-08-01 22:53:21 INFO: Downloaded file to /Users/mh/stanza_resources/resources.json
2024-08-01 22:53:21 INFO: Downloading default packages for language: en (English) ...
2024-08-01 22:53:25 INFO: File exists: /Users/mh/stanza_resources/en/default.zip
2024-08-01 22:53:32 INFO: Finished downloading models and saved to /Users/mh/stanza_resources
2024-08-01 22:53:32 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES


2024-08-01 22:53:35 INFO: Downloaded file to /Users/mh/stanza_resources/resources.json
2024-08-01 22:53:35 WARNING: Language en package default expects mwt, which has been added
2024-08-01 22:53:36 INFO: Loading these models for language: en (English):
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| pos       | combined_charlm   |
| lemma     | combined_nocharlm |
| depparse  | combined_charlm   |

2024-08-01 22:53:36 INFO: Using device: cpu
2024-08-01 22:53:36 INFO: Loading: tokenize
2024-08-01 22:53:36 INFO: Loading: mwt
2024-08-01 22:53:36 INFO: Loading: pos
2024-08-01 22:53:37 INFO: Loading: lemma
2024-08-01 22:53:37 INFO: Loading: depparse
2024-08-01 22:53:37 INFO: Done loading processors!


Sentence: I love learning about natural language processing
Word: I, Head: 2, Relation: nsubj
Word: love, Head: 0, Relation: root
Word: learning, Head: 2, Relation: xcomp
Word: about, Head: 7, Relation: case
Word: natural, Head: 6, Relation: amod
Word: language, Head: 7, Relation: compound
Word: processing, Head: 3, Relation: obl


'dependency_tree_en.png'

In [101]:
# Download and load the Chinese model
stanza.download('tr')
nlp3 = stanza.Pipeline(lang='tr', processors='tokenize,pos,lemma,depparse')

text_tr = "Doğal dil işleme çalışmalarını seviyorum"
doc_tr = nlp3(text_tr)

# Function to visualize the dependency tree
def visualize_dependency_tree(doc):
    dot = Digraph()

    for sentence in doc.sentences:
        for word in sentence.words:
            dot.node(str(word.id), word.text)
            if word.head > 0:
                dot.edge(str(word.head), str(word.id), label=word.deprel)

    return dot

# Extract and print dependency relations
for sentence in doc_ch.sentences:
    print(f"Sentence: {sentence.text}")
    for word in sentence.words:
        print(f"Word: {word.text}, Head: {word.head}, Relation: {word.deprel}")

dot = visualize_dependency_tree(doc_tr)
dot.render('dependency_tree_tr', format='png', view=True)  


2024-08-01 22:53:39 INFO: Downloaded file to /Users/mh/stanza_resources/resources.json
2024-08-01 22:53:39 INFO: Downloading default packages for language: tr (Turkish) ...
2024-08-01 22:53:42 INFO: File exists: /Users/mh/stanza_resources/tr/default.zip
2024-08-01 22:53:47 INFO: Finished downloading models and saved to /Users/mh/stanza_resources
2024-08-01 22:53:47 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES


2024-08-01 22:53:48 INFO: Downloaded file to /Users/mh/stanza_resources/resources.json
2024-08-01 22:53:48 WARNING: Language tr package default expects mwt, which has been added
2024-08-01 22:53:49 INFO: Loading these models for language: tr (Turkish):
| Processor | Package       |
-----------------------------
| tokenize  | imst          |
| mwt       | imst          |
| pos       | imst_charlm   |
| lemma     | imst_nocharlm |
| depparse  | imst_charlm   |

2024-08-01 22:53:49 INFO: Using device: cpu
2024-08-01 22:53:49 INFO: Loading: tokenize
2024-08-01 22:53:49 INFO: Loading: mwt
2024-08-01 22:53:49 INFO: Loading: pos
2024-08-01 22:53:49 INFO: Loading: lemma
2024-08-01 22:53:49 INFO: Loading: depparse
2024-08-01 22:53:50 INFO: Done loading processors!


Sentence: 我喜欢学习自然语言处理
Word: 我, Head: 2, Relation: nsubj
Word: 喜欢, Head: 0, Relation: root
Word: 学习, Head: 6, Relation: advcl
Word: 自然, Head: 5, Relation: nmod
Word: 语言, Head: 3, Relation: obj
Word: 处理, Head: 2, Relation: xcomp


'dependency_tree_tr.png'